const jokesArray = [
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why don’t skeletons ever fight each other? They don’t have the guts.",
    "What did the sushi say to the bee? Wasabi!",
    "Why did the bicycle fall over? Because it was two-tired.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What did the ocean say to the beach? Nothing, it just waved!",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "What do you call a monkey who loves potato chips? A chipmunk!",
    "Why was the math book sad? Because it had too many problems!",
    "What do you call an alligator in a vest? An investigator.",
    "How does a lion like his steak? Rare.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "What do you call an angry pea? Grumpy.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why do bicycles fall over? Because they are two-tired.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why don’t skeletons go to parties? They have no body to go with.",
    "Why did the dog sit in the shade? Because he didn’t want to be a hot dog!",
    "Why don’t eggs tell jokes? They might crack up.",
    "What’s brown and sticky? A stick!",
    "What do you call a fish who practices medicine? A sturgeon!",
    "What did one hat say to the other? Stay here, I’m going on ahead!",
    "Why can’t you trust stairs? They’re always up to something.",
    "Why did the cookie go to the hospital? Because it felt crummy!",
    "Why did the banana go to the doctor? Because it wasn’t peeling well!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the coffee file a police report? It got mugged!",
    "Why don’t skeletons ever go trick-or-treating? Because they have no body to go with!",
    "How do you make a lemon drop? Just let it fall!",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the frog call his insurance company? He had a jump in his car!",
    "What do you call an alligator in a vest? An investigator.",
    "What did one volcano say to another? I lava you.",
    "What do you call a dog magician? A labracadabrador.",
    "Why do cows wear bells? Because their horns don’t work!",
    "Why don’t skeletons go to parties? They have no body to go with.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "Why was the computer cold? It left its Windows open!",
    "Why don’t ghosts like to go out in the rain? It dampens their spirits.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "What did the grape stop in the middle of the road? It ran out of juice!",
    "Why do chickens stay in the coop? Because it’s too late to leave!",
    "What do you call a dog magician? A labracadabrador.",
    "Why did the dog sit in the shade? Because he didn’t want to be a hot dog.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why don’t you ever see any hippos hiding in trees? Because they're really, really good at it.",
    "What did one volcano say to the other? I lava you.",
    "Why did the cookie go to the hospital? Because it felt crummy!",
    "Why did the frog call his insurance company? He had a jump in his car!",
    "Why was the math book sad? Because it had too many problems!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What’s a skeleton’s least favorite room in the house? The living room.",
    "How do you make a tissue dance? Put a little boogie in it!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why don’t you ever see any hippos hiding in trees? Because they’re really, really good at it.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the bicycle fall over? Because it was two-tired.",
    "Why was the computer cold? It left its Windows open!",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the frog call his insurance company? He had a jump in his car!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you call an angry pea? Grumpy.",
    "Why don’t skeletons go to parties? They have no body to go with.",
    "What did the cookie go to the hospital? Because it felt crummy!",
    "What do you call a sleeping bull? A bulldozer!",
    "Why do chickens only have two doors? Because if they had four, they’d be chicken sedans!",
    "Why can’t a nose be 12 inches long? Because then it would be a foot.",
    "What do you call an angry pea? Grumpy.",
    "Why don’t skeletons ever go trick or treating? Because they have no body to go with!",
    "What do you call an alligator in a vest? An investigator.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the skeleton go to the party alone? He had no body to go with him.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the dog sit in the shade? Because he didn’t want to be a hot dog.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why did the skeleton wear a bone suit? Because it was his best fit!",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why don’t you ever see any hippos hiding in trees? Because they’re really, really good at it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the dog sit in the shade? Because he didn’t want to be a hot dog.",
    "What do you call a dog magician? A labracadabrador.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why was the math book sad? Because it had too many problems!"
  ];

let jokeNum = Math.floor(Math.random()*jokesArray.length);
let joke = jokesArray[jokeNum];

document.getElementsByClassName("joke")[0].innerHTML = `<div style="font-size:30px; margin-left: 10px;">"${joke}"</div>`;